version : '2'

services :
    apache1:
        build: .
        ports:
          - "5000:80"
        volumes:
          - .:/var/www/html

    mysql:
        image: mysql
        environment:
           MYSQL_ROOT_PASSWORD: password


